In [1]:
import datetime as dt
import pytz
from ml_storm_surge_operational.mains.main_predict import main

2025-05-25 12:16:35.835124: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
datetime_predict = '2025-05-19 00:00'
datetime_predict = (
        dt.datetime
        .strptime(datetime_predict, "%Y-%m-%d %H:%M")
        .replace(tzinfo=pytz.UTC)
    )
datetime_predict

datetime.datetime(2025, 5, 19, 0, 0, tzinfo=<UTC>)

In [3]:
main(datetime_predict)

--- station: NO_OSC
Call PrepareDataFrames...
Preparing feature and label df...
Preparing auxiliary DataFrame...
Generating obs and tide_py DataFrame form operational data for the past...
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 0 start:  0 end:  144 var: observed_at_chartdatum
[0.36999997 0.30999997 0.30999997 0.34999996 0.39999998 0.40999997
 0.45999998 0.53999996 0.59       0.57       0.51       0.43999997
 0.37999997 0.32       0.29       0.29999998 0.33999997 0.35999998
 0.37999997 0.43999997 0.51       0.53999996 0.53       0.48999998]
var: observed_at_chartdatum
path_list[i]: /lustre/storeB/project/metproduction/products/util/vannstand//kyststasjoner_norge.nc2025051800
i: 0 j: 1 start:  6 end:  150 var: observed_at_chartdatum
[0.30999997 0.30999997 0.34999996 0.39999998 0.40999997 0.45999998
 0.53999996 0.59       0.57       0.51       0.43999997 0.37999997
 0.32       0.29   

2025-05-25 12:16:44.639596: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2025-05-25 12:16:44.642476: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2025-05-25 12:16:44.642489: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2025-05-25 12:16:44.642509: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ppi-r8login-b2.int.met.no): /proc/driver/nvidia/version does not exist
2025-05-25 12:16:44.642980: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations,

--- y_test_norm_pred.shape: (1, 1)
--- y_train_mean[t - 1].shape: ()
--- y_train_std[t - 1].shape: ()
--- y_test_pred.shape: tf.Tensor([[-0.0007597]], shape=(1, 1), dtype=float32)
--- y_test_norm_pred: tf.Tensor([[-0.13122346]], shape=(1, 1), dtype=float32)
--- y_train_mean[t - 1]: 0.007546375824607386
--- y_train_std[t - 1]: 0.06329717019988483
--- y_test_pred: tf.Tensor([[-0.0007597]], shape=(1, 1), dtype=float32)
--- y_test_norm_pred.shape: (1, 1)
--- y_train_mean[t - 1].shape: ()
--- y_train_std[t - 1].shape: ()
--- y_test_pred.shape: tf.Tensor([[0.04166753]], shape=(1, 1), dtype=float32)
--- y_test_norm_pred: tf.Tensor([[0.5142642]], shape=(1, 1), dtype=float32)
--- y_train_mean[t - 1]: 0.008590765421034095
--- y_train_std[t - 1]: 0.06431861072664442
--- y_test_pred: tf.Tensor([[0.04166753]], shape=(1, 1), dtype=float32)
--- y_test_norm_pred.shape: (1, 1)
--- y_train_mean[t - 1].shape: ()
--- y_train_std[t - 1].shape: ()
--- y_test_pred.shape: tf.Tensor([[0.02571218]], shape=(1, 1